apiVersion: v1
kind: ConfigMap
metadata:
  name: sampleconf
data:
  server.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <server description="new server">

     <!-- Enable features -->
     <featureManager>
        <feature>jakartaee-10.0</feature>
     </featureManager>

     <basicRegistry id="basic" realm="BasicRealm"> 
        <!-- <user name="yourUserName" password="" />  --> 
     </basicRegistry>
   
     <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
     <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="9080" httpsPort="9443"/>

     <applicationManager autoExpand="true"/>

     <!-- Default SSL configuration enables trust for default certificates from the Java runtime --> 
     <ssl id="defaultSSLConfig" trustDefaultCerts="true"/>

     <keyStore id="defaultKeyStore" password="{xor}Pi0rOjI2LG9nZmY=" />

     <applicationMonitor updateTrigger="mbean"/>

    </server>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledep
spec:
  selector:
    matchLabels:
      app: sampleapp
  replicas: 1
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: samplecon
          image: default-route-openshift-image-registry.apps-crc.testing/project1/sampleapp1
          ports:
          - containerPort: 9080
          volumeMounts:
            - mountPath: /config/server.xml
              subPath: server.xml
              name: config-vol
      volumes:
        - name: config-vol
          configMap:
            name: sampleconf
---
apiVersion: v1
kind: Service
metadata:
  name: sampleser
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
      nodePort: 30080
  selector:
    app: sampleapp
