kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "sampleapp1-build" 
spec:
  triggers: 
    - type: ConfigChange
  source:
    type: Git 
    git:
      uri: "https://github.com/chocopon0899/SampleApp.git"
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: websphere-liberty:full-java8-ibmjava
    type: Docker
  output: 
    to:
      kind: "ImageStreamTag"
      name: "sampleapp1:latest"
