kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "sampleapp1-build" 
spec:
  triggers: 
    - type: ConfigChange
  source:
    type: Dockerfile
    dockerfile: |
      FROM wasliberty
      COPY SampleApp.war /config/dropins/
  strategy:
    type: Docker
  output: 
    to:
      kind: "ImageStreamTag"
      name: "sampleapp1:latest"
