apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledep
spec:
  selector:
    matchLabels:
      app: sampleapp
  replicas: 1
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: samplecon
          image: sampleapp1
          ports:
          - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: sampleser
spec:
  type: NodePort
  ports:
    - port: 8099
      targetPort: 9080
      protocol: TCP
      nodePort: 30080
  selector:
    app: sampleapp
