kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "sampleapp1-build" 
spec:
  triggers: 
    - type: ConfigChange
  source:
    type: Dockerfile
    dockerfile: |
      FROM websphere-liberty:full-java8-ibmjava
      COPY SampleApp.war /config/dropins/
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: websphere-liberty:full-java8-ibmjava
    type: Docker
  output: 
    to:
      kind: "ImageStreamTag"
      name: "sampleapp1:latest"
